version: "3.7"

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        restart: always
        volumes:
            - /jenkins:/var/jenkins_home
        ports:
            - 8081:8080
        privileged: true
        user: root
