version: "3.7"

services:
    redis:
        image: redis
        command: redis-server --requirepass 1234 --port 6379
        container_name: redis
        restart: always
        ports:
            - 6379:6379
